package main

type MetricDefinition struct {
	ATSKey string
	Name   string
	Help   string
}

var MetricDefinitions = []MetricDefinition{
	// HTTP Connections
	{ATSKey: "proxy.process.http.total_client_connections", Name: "ats_http_total_client_connections", Help: "Total number of client connections"},
	{ATSKey: "proxy.process.http.total_client_connections_ipv4", Name: "ats_http_total_client_connections_ipv4", Help: "Total client connections over IPv4"},
	{ATSKey: "proxy.process.http.total_client_connections_ipv6", Name: "ats_http_total_client_connections_ipv6", Help: "Total client connections over IPv6"},
	{ATSKey: "proxy.process.http.total_incoming_connections", Name: "ats_http_total_incoming_connections", Help: "Total incoming connections"},
	{ATSKey: "proxy.process.http.total_server_connections", Name: "ats_http_total_server_connections", Help: "Total server connections"},
	{ATSKey: "proxy.process.http.total_parent_proxy_connections", Name: "ats_http_total_parent_proxy_connections", Help: "Total parent proxy connections"},
	{ATSKey: "proxy.process.http.total_parent_retries", Name: "ats_http_total_parent_retries", Help: "Total parent retries"},
	{ATSKey: "proxy.process.http.total_parent_switches", Name: "ats_http_total_parent_switches", Help: "Total parent switches"},
	{ATSKey: "proxy.process.http.total_parent_retries_exhausted", Name: "ats_http_total_parent_retries_exhausted", Help: "Total parent retries exhausted"},
	{ATSKey: "proxy.process.http.total_parent_marked_down_count", Name: "ats_http_total_parent_marked_down_count", Help: "Total parent marked down count"},
	{ATSKey: "proxy.process.http.current_client_connections", Name: "ats_http_current_client_connections", Help: "Current client connections"},
	{ATSKey: "proxy.process.http.current_active_client_connections", Name: "ats_http_current_active_client_connections", Help: "Current active client connections"},
	{ATSKey: "proxy.process.http.current_server_connections", Name: "ats_http_current_server_connections", Help: "Current server connections"},
	{ATSKey: "proxy.process.http.current_cache_connections", Name: "ats_http_current_cache_connections", Help: "Current cache connections"},
	{ATSKey: "proxy.process.http.current_client_transactions", Name: "ats_http_current_client_transactions", Help: "Current client transactions"},
	{ATSKey: "proxy.process.http.current_server_transactions", Name: "ats_http_current_server_transactions", Help: "Current server transactions"},
	{ATSKey: "proxy.process.http.current_parent_proxy_connections", Name: "ats_http_current_parent_proxy_connections", Help: "Current parent proxy connections"},
	{ATSKey: "proxy.process.http.pooled_server_connections", Name: "ats_http_pooled_server_connections", Help: "Pooled server connections"},
	{ATSKey: "proxy.process.http.avg_transactions_per_client_connection", Name: "ats_http_avg_transactions_per_client_connection", Help: "Average transactions per client connection"},
	{ATSKey: "proxy.process.http.avg_transactions_per_server_connection", Name: "ats_http_avg_transactions_per_server_connection", Help: "Average transactions per server connection"},
	{ATSKey: "proxy.process.http.websocket.current_active_client_connections", Name: "ats_http_websocket_current_active_client_connections", Help: "Current active WebSocket client connections"},

	// HTTP Requests
	{ATSKey: "proxy.process.http.completed_requests", Name: "ats_http_completed_requests", Help: "Completed requests"},
	{ATSKey: "proxy.process.http.incoming_requests", Name: "ats_http_incoming_requests", Help: "Incoming HTTP requests"},
	{ATSKey: "proxy.process.http.outgoing_requests", Name: "ats_http_outgoing_requests", Help: "Outgoing HTTP requests"},
	{ATSKey: "proxy.process.http.incoming_responses", Name: "ats_http_incoming_responses", Help: "Incoming responses"},
	{ATSKey: "proxy.process.http.invalid_client_requests", Name: "ats_http_invalid_client_requests", Help: "Invalid client requests"},
	{ATSKey: "proxy.process.http.missing_host_hdr", Name: "ats_http_missing_host_hdr", Help: "Missing host header"},
	{ATSKey: "proxy.process.http.get_requests", Name: "ats_http_get_requests", Help: "GET requests"},
	{ATSKey: "proxy.process.http.head_requests", Name: "ats_http_head_requests", Help: "HEAD requests"},
	{ATSKey: "proxy.process.http.post_requests", Name: "ats_http_post_requests", Help: "POST requests"},
	{ATSKey: "proxy.process.http.put_requests", Name: "ats_http_put_requests", Help: "PUT requests"},
	{ATSKey: "proxy.process.http.delete_requests", Name: "ats_http_delete_requests", Help: "DELETE requests"},
	{ATSKey: "proxy.process.http.options_requests", Name: "ats_http_options_requests", Help: "OPTIONS requests"},
	{ATSKey: "proxy.process.http.trace_requests", Name: "ats_http_trace_requests", Help: "TRACE requests"},
	{ATSKey: "proxy.process.http.connect_requests", Name: "ats_http_connect_requests", Help: "CONNECT requests"},
	{ATSKey: "proxy.process.http.push_requests", Name: "ats_http_push_requests", Help: "PUSH requests"},
	{ATSKey: "proxy.process.http.purge_requests", Name: "ats_http_purge_requests", Help: "PURGE requests"},
	{ATSKey: "proxy.process.http.extension_method_requests", Name: "ats_http_extension_method_requests", Help: "Extension method requests"},

	// HTTP Responses
	{ATSKey: "proxy.process.http.1xx_responses", Name: "ats_http_1xx_responses", Help: "1xx responses"},
	{ATSKey: "proxy.process.http.100_responses", Name: "ats_http_100_responses", Help: "100 responses"},
	{ATSKey: "proxy.process.http.101_responses", Name: "ats_http_101_responses", Help: "101 responses"},
	{ATSKey: "proxy.process.http.2xx_responses", Name: "ats_http_2xx_responses", Help: "2xx responses"},
	{ATSKey: "proxy.process.http.200_responses", Name: "ats_http_200_responses", Help: "200 responses"},
	{ATSKey: "proxy.process.http.201_responses", Name: "ats_http_201_responses", Help: "201 responses"},
	{ATSKey: "proxy.process.http.202_responses", Name: "ats_http_202_responses", Help: "202 responses"},
	{ATSKey: "proxy.process.http.203_responses", Name: "ats_http_203_responses", Help: "203 responses"},
	{ATSKey: "proxy.process.http.204_responses", Name: "ats_http_204_responses", Help: "204 responses"},
	{ATSKey: "proxy.process.http.205_responses", Name: "ats_http_205_responses", Help: "205 responses"},
	{ATSKey: "proxy.process.http.206_responses", Name: "ats_http_206_responses", Help: "206 responses"},
	{ATSKey: "proxy.process.http.3xx_responses", Name: "ats_http_3xx_responses", Help: "3xx responses"},
	{ATSKey: "proxy.process.http.300_responses", Name: "ats_http_300_responses", Help: "300 responses"},
	{ATSKey: "proxy.process.http.301_responses", Name: "ats_http_301_responses", Help: "301 responses"},
	{ATSKey: "proxy.process.http.302_responses", Name: "ats_http_302_responses", Help: "302 responses"},
	{ATSKey: "proxy.process.http.303_responses", Name: "ats_http_303_responses", Help: "303 responses"},
	{ATSKey: "proxy.process.http.304_responses", Name: "ats_http_304_responses", Help: "304 responses"},
	{ATSKey: "proxy.process.http.305_responses", Name: "ats_http_305_responses", Help: "305 responses"},
	{ATSKey: "proxy.process.http.307_responses", Name: "ats_http_307_responses", Help: "307 responses"},
	{ATSKey: "proxy.process.http.308_responses", Name: "ats_http_308_responses", Help: "308 responses"},
	{ATSKey: "proxy.process.http.4xx_responses", Name: "ats_http_4xx_responses", Help: "4xx responses"},
	{ATSKey: "proxy.process.http.400_responses", Name: "ats_http_400_responses", Help: "400 responses"},
	{ATSKey: "proxy.process.http.401_responses", Name: "ats_http_401_responses", Help: "401 responses"},
	{ATSKey: "proxy.process.http.402_responses", Name: "ats_http_402_responses", Help: "402 responses"},
	{ATSKey: "proxy.process.http.403_responses", Name: "ats_http_403_responses", Help: "403 responses"},
	{ATSKey: "proxy.process.http.404_responses", Name: "ats_http_404_responses", Help: "404 responses"},
	{ATSKey: "proxy.process.http.405_responses", Name: "ats_http_405_responses", Help: "405 responses"},
	{ATSKey: "proxy.process.http.406_responses", Name: "ats_http_406_responses", Help: "406 responses"},
	{ATSKey: "proxy.process.http.407_responses", Name: "ats_http_407_responses", Help: "407 responses"},
	{ATSKey: "proxy.process.http.408_responses", Name: "ats_http_408_responses", Help: "408 responses"},
	{ATSKey: "proxy.process.http.409_responses", Name: "ats_http_409_responses", Help: "409 responses"},
	{ATSKey: "proxy.process.http.410_responses", Name: "ats_http_410_responses", Help: "410 responses"},
	{ATSKey: "proxy.process.http.411_responses", Name: "ats_http_411_responses", Help: "411 responses"},
	{ATSKey: "proxy.process.http.412_responses", Name: "ats_http_412_responses", Help: "412 responses"},
	{ATSKey: "proxy.process.http.413_responses", Name: "ats_http_413_responses", Help: "413 responses"},
	{ATSKey: "proxy.process.http.414_responses", Name: "ats_http_414_responses", Help: "414 responses"},
	{ATSKey: "proxy.process.http.415_responses", Name: "ats_http_415_responses", Help: "415 responses"},
	{ATSKey: "proxy.process.http.416_responses", Name: "ats_http_416_responses", Help: "416 responses"},
	{ATSKey: "proxy.process.http.5xx_responses", Name: "ats_http_5xx_responses", Help: "5xx responses"},
	{ATSKey: "proxy.process.http.500_responses", Name: "ats_http_500_responses", Help: "500 responses"},
	{ATSKey: "proxy.process.http.501_responses", Name: "ats_http_501_responses", Help: "501 responses"},
	{ATSKey: "proxy.process.http.502_responses", Name: "ats_http_502_responses", Help: "502 responses"},
	{ATSKey: "proxy.process.http.503_responses", Name: "ats_http_503_responses", Help: "503 responses"},
	{ATSKey: "proxy.process.http.504_responses", Name: "ats_http_504_responses", Help: "504 responses"},
	{ATSKey: "proxy.process.http.505_responses", Name: "ats_http_505_responses", Help: "505 responses"},

	// HTTP Bytes
	{ATSKey: "proxy.process.http.user_agent_request_header_total_size", Name: "ats_http_user_agent_request_header_bytes", Help: "User agent request header total bytes"},
	{ATSKey: "proxy.process.http.user_agent_request_document_total_size", Name: "ats_http_user_agent_request_document_bytes", Help: "User agent request document total bytes"},
	{ATSKey: "proxy.process.http.user_agent_response_header_total_size", Name: "ats_http_user_agent_response_header_bytes", Help: "User agent response header total bytes"},
	{ATSKey: "proxy.process.http.user_agent_response_document_total_size", Name: "ats_http_user_agent_response_document_bytes", Help: "User agent response document total bytes"},
	{ATSKey: "proxy.process.http.user_agent_total_request_bytes", Name: "ats_http_user_agent_total_request_bytes", Help: "User agent total request bytes"},
	{ATSKey: "proxy.process.http.user_agent_total_response_bytes", Name: "ats_http_user_agent_total_response_bytes", Help: "User agent total response bytes"},
	{ATSKey: "proxy.process.http.origin_server_request_header_total_size", Name: "ats_http_origin_server_request_header_bytes", Help: "Origin server request header total bytes"},
	{ATSKey: "proxy.process.http.origin_server_request_document_total_size", Name: "ats_http_origin_server_request_document_bytes", Help: "Origin server request document total bytes"},
	{ATSKey: "proxy.process.http.origin_server_response_header_total_size", Name: "ats_http_origin_server_response_header_bytes", Help: "Origin server response header total bytes"},
	{ATSKey: "proxy.process.http.origin_server_response_document_total_size", Name: "ats_http_origin_server_response_document_bytes", Help: "Origin server response document total bytes"},
	{ATSKey: "proxy.process.http.origin_server_total_request_bytes", Name: "ats_http_origin_server_total_request_bytes", Help: "Origin server total request bytes"},
	{ATSKey: "proxy.process.http.origin_server_total_response_bytes", Name: "ats_http_origin_server_total_response_bytes", Help: "Origin server total response bytes"},
	{ATSKey: "proxy.process.http.parent_proxy_request_total_bytes", Name: "ats_http_parent_proxy_request_bytes", Help: "Parent proxy request total bytes"},
	{ATSKey: "proxy.process.http.parent_proxy_response_total_bytes", Name: "ats_http_parent_proxy_response_bytes", Help: "Parent proxy response total bytes"},
	{ATSKey: "proxy.process.http.pushed_response_header_total_size", Name: "ats_http_pushed_response_header_bytes", Help: "Pushed response header total bytes"},
	{ATSKey: "proxy.process.http.pushed_document_total_size", Name: "ats_http_pushed_document_bytes", Help: "Pushed document total bytes"},

	// HTTP Document Size Distribution
	{ATSKey: "proxy.process.http.response_document_size_100", Name: "ats_http_response_document_size_100", Help: "Response documents <= 100 bytes"},
	{ATSKey: "proxy.process.http.response_document_size_1K", Name: "ats_http_response_document_size_1k", Help: "Response documents <= 1KB"},
	{ATSKey: "proxy.process.http.response_document_size_3K", Name: "ats_http_response_document_size_3k", Help: "Response documents <= 3KB"},
	{ATSKey: "proxy.process.http.response_document_size_5K", Name: "ats_http_response_document_size_5k", Help: "Response documents <= 5KB"},
	{ATSKey: "proxy.process.http.response_document_size_10K", Name: "ats_http_response_document_size_10k", Help: "Response documents <= 10KB"},
	{ATSKey: "proxy.process.http.response_document_size_1M", Name: "ats_http_response_document_size_1m", Help: "Response documents <= 1MB"},
	{ATSKey: "proxy.process.http.response_document_size_inf", Name: "ats_http_response_document_size_inf", Help: "Response documents > 1MB"},
	{ATSKey: "proxy.process.http.request_document_size_100", Name: "ats_http_request_document_size_100", Help: "Request documents <= 100 bytes"},
	{ATSKey: "proxy.process.http.request_document_size_1K", Name: "ats_http_request_document_size_1k", Help: "Request documents <= 1KB"},
	{ATSKey: "proxy.process.http.request_document_size_3K", Name: "ats_http_request_document_size_3k", Help: "Request documents <= 3KB"},
	{ATSKey: "proxy.process.http.request_document_size_5K", Name: "ats_http_request_document_size_5k", Help: "Request documents <= 5KB"},
	{ATSKey: "proxy.process.http.request_document_size_10K", Name: "ats_http_request_document_size_10k", Help: "Request documents <= 10KB"},
	{ATSKey: "proxy.process.http.request_document_size_1M", Name: "ats_http_request_document_size_1m", Help: "Request documents <= 1MB"},
	{ATSKey: "proxy.process.http.request_document_size_inf", Name: "ats_http_request_document_size_inf", Help: "Request documents > 1MB"},

	// HTTP Speed Distribution
	{ATSKey: "proxy.process.http.user_agent_speed_bytes_per_sec_100", Name: "ats_http_user_agent_speed_100", Help: "User agent speed <= 100 B/s"},
	{ATSKey: "proxy.process.http.user_agent_speed_bytes_per_sec_1K", Name: "ats_http_user_agent_speed_1k", Help: "User agent speed <= 1 KB/s"},
	{ATSKey: "proxy.process.http.user_agent_speed_bytes_per_sec_10K", Name: "ats_http_user_agent_speed_10k", Help: "User agent speed <= 10 KB/s"},
	{ATSKey: "proxy.process.http.user_agent_speed_bytes_per_sec_100K", Name: "ats_http_user_agent_speed_100k", Help: "User agent speed <= 100 KB/s"},
	{ATSKey: "proxy.process.http.user_agent_speed_bytes_per_sec_1M", Name: "ats_http_user_agent_speed_1m", Help: "User agent speed <= 1 MB/s"},
	{ATSKey: "proxy.process.http.user_agent_speed_bytes_per_sec_10M", Name: "ats_http_user_agent_speed_10m", Help: "User agent speed <= 10 MB/s"},
	{ATSKey: "proxy.process.http.user_agent_speed_bytes_per_sec_100M", Name: "ats_http_user_agent_speed_100m", Help: "User agent speed <= 100 MB/s"},
	{ATSKey: "proxy.process.http.origin_server_speed_bytes_per_sec_100", Name: "ats_http_origin_server_speed_100", Help: "Origin server speed <= 100 B/s"},
	{ATSKey: "proxy.process.http.origin_server_speed_bytes_per_sec_1K", Name: "ats_http_origin_server_speed_1k", Help: "Origin server speed <= 1 KB/s"},
	{ATSKey: "proxy.process.http.origin_server_speed_bytes_per_sec_10K", Name: "ats_http_origin_server_speed_10k", Help: "Origin server speed <= 10 KB/s"},
	{ATSKey: "proxy.process.http.origin_server_speed_bytes_per_sec_100K", Name: "ats_http_origin_server_speed_100k", Help: "Origin server speed <= 100 KB/s"},
	{ATSKey: "proxy.process.http.origin_server_speed_bytes_per_sec_1M", Name: "ats_http_origin_server_speed_1m", Help: "Origin server speed <= 1 MB/s"},
	{ATSKey: "proxy.process.http.origin_server_speed_bytes_per_sec_10M", Name: "ats_http_origin_server_speed_10m", Help: "Origin server speed <= 10 MB/s"},
	{ATSKey: "proxy.process.http.origin_server_speed_bytes_per_sec_100M", Name: "ats_http_origin_server_speed_100m", Help: "Origin server speed <= 100 MB/s"},

	// HTTP Cache
	{ATSKey: "proxy.process.http.cache_lookups", Name: "ats_http_cache_lookups", Help: "Cache lookups"},
	{ATSKey: "proxy.process.http.cache_writes", Name: "ats_http_cache_writes", Help: "Cache writes"},
	{ATSKey: "proxy.process.http.cache_updates", Name: "ats_http_cache_updates", Help: "Cache updates"},
	{ATSKey: "proxy.process.http.cache_deletes", Name: "ats_http_cache_deletes", Help: "Cache deletes"},
	{ATSKey: "proxy.process.http.cache_hit_fresh", Name: "ats_http_cache_hit_fresh", Help: "Cache hit fresh"},
	{ATSKey: "proxy.process.http.cache_hit_mem_fresh", Name: "ats_http_cache_hit_mem_fresh", Help: "Cache hit memory fresh"},
	{ATSKey: "proxy.process.http.cache_hit_rww", Name: "ats_http_cache_hit_rww", Help: "Cache hit read-while-write"},
	{ATSKey: "proxy.process.http.cache_hit_revalidated", Name: "ats_http_cache_hit_revalidated", Help: "Cache hit revalidated"},
	{ATSKey: "proxy.process.http.cache_hit_ims", Name: "ats_http_cache_hit_ims", Help: "Cache hit IMS"},
	{ATSKey: "proxy.process.http.cache_hit_stale_served", Name: "ats_http_cache_hit_stale_served", Help: "Cache hit stale served"},
	{ATSKey: "proxy.process.http.cache_miss_cold", Name: "ats_http_cache_miss_cold", Help: "Cache miss cold"},
	{ATSKey: "proxy.process.http.cache_miss_changed", Name: "ats_http_cache_miss_changed", Help: "Cache miss changed"},
	{ATSKey: "proxy.process.http.cache_miss_client_no_cache", Name: "ats_http_cache_miss_client_no_cache", Help: "Cache miss client no-cache"},
	{ATSKey: "proxy.process.http.cache_miss_client_not_cacheable", Name: "ats_http_cache_miss_client_not_cacheable", Help: "Cache miss client not cacheable"},
	{ATSKey: "proxy.process.http.cache_miss_ims", Name: "ats_http_cache_miss_ims", Help: "Cache miss IMS"},
	{ATSKey: "proxy.process.http.cache_read_error", Name: "ats_http_cache_read_error", Help: "Cache read errors"},
	{ATSKey: "proxy.process.http.cache_write_errors", Name: "ats_http_cache_write_errors", Help: "Cache write errors"},
	{ATSKey: "proxy.process.http.cache_read_errors", Name: "ats_http_cache_read_errors_total", Help: "Cache read errors"},

	// TCP Stats
	{ATSKey: "proxy.process.http.tcp_hit_count_stat", Name: "ats_http_tcp_hit_count", Help: "TCP hit count"},
	{ATSKey: "proxy.process.http.tcp_hit_user_agent_bytes_stat", Name: "ats_http_tcp_hit_user_agent_bytes", Help: "TCP hit user agent bytes"},
	{ATSKey: "proxy.process.http.tcp_hit_origin_server_bytes_stat", Name: "ats_http_tcp_hit_origin_server_bytes", Help: "TCP hit origin server bytes"},
	{ATSKey: "proxy.process.http.tcp_miss_count_stat", Name: "ats_http_tcp_miss_count", Help: "TCP miss count"},
	{ATSKey: "proxy.process.http.tcp_miss_user_agent_bytes_stat", Name: "ats_http_tcp_miss_user_agent_bytes", Help: "TCP miss user agent bytes"},
	{ATSKey: "proxy.process.http.tcp_miss_origin_server_bytes_stat", Name: "ats_http_tcp_miss_origin_server_bytes", Help: "TCP miss origin server bytes"},
	{ATSKey: "proxy.process.http.tcp_expired_miss_count_stat", Name: "ats_http_tcp_expired_miss_count", Help: "TCP expired miss count"},
	{ATSKey: "proxy.process.http.tcp_expired_miss_user_agent_bytes_stat", Name: "ats_http_tcp_expired_miss_user_agent_bytes", Help: "TCP expired miss user agent bytes"},
	{ATSKey: "proxy.process.http.tcp_expired_miss_origin_server_bytes_stat", Name: "ats_http_tcp_expired_miss_origin_server_bytes", Help: "TCP expired miss origin server bytes"},
	{ATSKey: "proxy.process.http.tcp_refresh_hit_count_stat", Name: "ats_http_tcp_refresh_hit_count", Help: "TCP refresh hit count"},
	{ATSKey: "proxy.process.http.tcp_refresh_hit_user_agent_bytes_stat", Name: "ats_http_tcp_refresh_hit_user_agent_bytes", Help: "TCP refresh hit user agent bytes"},
	{ATSKey: "proxy.process.http.tcp_refresh_hit_origin_server_bytes_stat", Name: "ats_http_tcp_refresh_hit_origin_server_bytes", Help: "TCP refresh hit origin server bytes"},
	{ATSKey: "proxy.process.http.tcp_refresh_miss_count_stat", Name: "ats_http_tcp_refresh_miss_count", Help: "TCP refresh miss count"},
	{ATSKey: "proxy.process.http.tcp_refresh_miss_user_agent_bytes_stat", Name: "ats_http_tcp_refresh_miss_user_agent_bytes", Help: "TCP refresh miss user agent bytes"},
	{ATSKey: "proxy.process.http.tcp_refresh_miss_origin_server_bytes_stat", Name: "ats_http_tcp_refresh_miss_origin_server_bytes", Help: "TCP refresh miss origin server bytes"},
	{ATSKey: "proxy.process.http.tcp_client_refresh_count_stat", Name: "ats_http_tcp_client_refresh_count", Help: "TCP client refresh count"},
	{ATSKey: "proxy.process.http.tcp_client_refresh_user_agent_bytes_stat", Name: "ats_http_tcp_client_refresh_user_agent_bytes", Help: "TCP client refresh user agent bytes"},
	{ATSKey: "proxy.process.http.tcp_client_refresh_origin_server_bytes_stat", Name: "ats_http_tcp_client_refresh_origin_server_bytes", Help: "TCP client refresh origin server bytes"},
	{ATSKey: "proxy.process.http.tcp_ims_hit_count_stat", Name: "ats_http_tcp_ims_hit_count", Help: "TCP IMS hit count"},
	{ATSKey: "proxy.process.http.tcp_ims_hit_user_agent_bytes_stat", Name: "ats_http_tcp_ims_hit_user_agent_bytes", Help: "TCP IMS hit user agent bytes"},
	{ATSKey: "proxy.process.http.tcp_ims_hit_origin_server_bytes_stat", Name: "ats_http_tcp_ims_hit_origin_server_bytes", Help: "TCP IMS hit origin server bytes"},
	{ATSKey: "proxy.process.http.tcp_ims_miss_count_stat", Name: "ats_http_tcp_ims_miss_count", Help: "TCP IMS miss count"},
	{ATSKey: "proxy.process.http.tcp_ims_miss_user_agent_bytes_stat", Name: "ats_http_tcp_ims_miss_user_agent_bytes", Help: "TCP IMS miss user agent bytes"},
	{ATSKey: "proxy.process.http.tcp_ims_miss_origin_server_bytes_stat", Name: "ats_http_tcp_ims_miss_origin_server_bytes", Help: "TCP IMS miss origin server bytes"},

	// Errors
	{ATSKey: "proxy.process.http.err_client_abort_count_stat", Name: "ats_http_err_client_abort_count", Help: "Client abort errors"},
	{ATSKey: "proxy.process.http.err_client_abort_user_agent_bytes_stat", Name: "ats_http_err_client_abort_user_agent_bytes", Help: "Client abort user agent bytes"},
	{ATSKey: "proxy.process.http.err_client_abort_origin_server_bytes_stat", Name: "ats_http_err_client_abort_origin_server_bytes", Help: "Client abort origin server bytes"},
	{ATSKey: "proxy.process.http.err_client_read_error_count_stat", Name: "ats_http_err_client_read_error_count", Help: "Client read errors"},
	{ATSKey: "proxy.process.http.err_client_read_error_user_agent_bytes_stat", Name: "ats_http_err_client_read_error_user_agent_bytes", Help: "Client read error user agent bytes"},
	{ATSKey: "proxy.process.http.err_client_read_error_origin_server_bytes_stat", Name: "ats_http_err_client_read_error_origin_server_bytes", Help: "Client read error origin server bytes"},
	{ATSKey: "proxy.process.http.err_connect_fail_count_stat", Name: "ats_http_err_connect_fail_count", Help: "Connect fail errors"},
	{ATSKey: "proxy.process.http.err_connect_fail_user_agent_bytes_stat", Name: "ats_http_err_connect_fail_user_agent_bytes", Help: "Connect fail user agent bytes"},
	{ATSKey: "proxy.process.http.err_connect_fail_origin_server_bytes_stat", Name: "ats_http_err_connect_fail_origin_server_bytes", Help: "Connect fail origin server bytes"},
	{ATSKey: "proxy.process.http.broken_server_connections", Name: "ats_http_broken_server_connections", Help: "Broken server connections"},
	{ATSKey: "proxy.process.http.http_proxy_loop_detected", Name: "ats_http_proxy_loop_detected", Help: "HTTP proxy loop detected"},
	{ATSKey: "proxy.process.http.http_proxy_mh_loop_detected", Name: "ats_http_proxy_mh_loop_detected", Help: "HTTP proxy multi-hop loop detected"},

	// Misc Stats
	{ATSKey: "proxy.process.http.misc_count_stat", Name: "ats_http_misc_count", Help: "Miscellaneous count"},
	{ATSKey: "proxy.process.http.misc_user_agent_bytes_stat", Name: "ats_http_misc_user_agent_bytes", Help: "Miscellaneous user agent bytes"},
	{ATSKey: "proxy.process.http.http_misc_origin_server_bytes_stat", Name: "ats_http_misc_origin_server_bytes", Help: "Miscellaneous origin server bytes"},

	// HTTP Tunnels & Background Fill
	{ATSKey: "proxy.process.http.tunnels", Name: "ats_http_tunnels", Help: "HTTP tunnels"},
	{ATSKey: "proxy.process.http.background_fill_total_count", Name: "ats_http_background_fill_total_count", Help: "Background fill total count"},
	{ATSKey: "proxy.process.http.background_fill_current_count", Name: "ats_http_background_fill_current_count", Help: "Background fill current count"},
	{ATSKey: "proxy.process.http.background_fill_bytes_aborted_stat", Name: "ats_http_background_fill_bytes_aborted", Help: "Background fill bytes aborted"},
	{ATSKey: "proxy.process.http.background_fill_bytes_completed_stat", Name: "ats_http_background_fill_bytes_completed", Help: "Background fill bytes completed"},

	// Transaction Time
	{ATSKey: "proxy.process.http.total_transactions_time", Name: "ats_http_total_transactions_time", Help: "Total transactions time (ns)"},
	{ATSKey: "proxy.process.http.parent_proxy_transaction_time", Name: "ats_http_parent_proxy_transaction_time", Help: "Parent proxy transaction time"},
	{ATSKey: "proxy.process.http.transaction_counts.errors.pre_accept_hangups", Name: "ats_http_transaction_errors_pre_accept_hangups_count", Help: "Transaction errors pre-accept hangups count"},
	{ATSKey: "proxy.process.http.transaction_totaltime.errors.pre_accept_hangups", Name: "ats_http_transaction_errors_pre_accept_hangups_time", Help: "Transaction errors pre-accept hangups time"},
	{ATSKey: "proxy.process.http.transaction_counts.hit_fresh", Name: "ats_http_transaction_hit_fresh_count", Help: "Transaction hit fresh count"},
	{ATSKey: "proxy.process.http.transaction_totaltime.hit_fresh", Name: "ats_http_transaction_hit_fresh_time", Help: "Transaction hit fresh time"},
	{ATSKey: "proxy.process.http.transaction_counts.hit_fresh.process", Name: "ats_http_transaction_hit_fresh_process_count", Help: "Transaction hit fresh process count"},
	{ATSKey: "proxy.process.http.transaction_totaltime.hit_fresh.process", Name: "ats_http_transaction_hit_fresh_process_time", Help: "Transaction hit fresh process time"},
	{ATSKey: "proxy.process.http.transaction_counts.hit_revalidated", Name: "ats_http_transaction_hit_revalidated_count", Help: "Transaction hit revalidated count"},
	{ATSKey: "proxy.process.http.transaction_totaltime.hit_revalidated", Name: "ats_http_transaction_hit_revalidated_time", Help: "Transaction hit revalidated time"},
	{ATSKey: "proxy.process.http.transaction_counts.miss_cold", Name: "ats_http_transaction_miss_cold_count", Help: "Transaction miss cold count"},
	{ATSKey: "proxy.process.http.transaction_totaltime.miss_cold", Name: "ats_http_transaction_miss_cold_time", Help: "Transaction miss cold time"},
	{ATSKey: "proxy.process.http.transaction_counts.miss_not_cacheable", Name: "ats_http_transaction_miss_not_cacheable_count", Help: "Transaction miss not cacheable count"},
	{ATSKey: "proxy.process.http.transaction_totaltime.miss_not_cacheable", Name: "ats_http_transaction_miss_not_cacheable_time", Help: "Transaction miss not cacheable time"},
	{ATSKey: "proxy.process.http.transaction_counts.miss_changed", Name: "ats_http_transaction_miss_changed_count", Help: "Transaction miss changed count"},
	{ATSKey: "proxy.process.http.transaction_totaltime.miss_changed", Name: "ats_http_transaction_miss_changed_time", Help: "Transaction miss changed time"},
	{ATSKey: "proxy.process.http.transaction_counts.miss_client_no_cache", Name: "ats_http_transaction_miss_client_no_cache_count", Help: "Transaction miss client no-cache count"},
	{ATSKey: "proxy.process.http.transaction_totaltime.miss_client_no_cache", Name: "ats_http_transaction_miss_client_no_cache_time", Help: "Transaction miss client no-cache time"},
	{ATSKey: "proxy.process.http.transaction_counts.errors.aborts", Name: "ats_http_transaction_errors_aborts_count", Help: "Transaction errors aborts count"},
	{ATSKey: "proxy.process.http.transaction_totaltime.errors.aborts", Name: "ats_http_transaction_errors_aborts_time", Help: "Transaction errors aborts time"},
	{ATSKey: "proxy.process.http.transaction_counts.errors.possible_aborts", Name: "ats_http_transaction_errors_possible_aborts_count", Help: "Transaction errors possible aborts count"},
	{ATSKey: "proxy.process.http.transaction_totaltime.errors.possible_aborts", Name: "ats_http_transaction_errors_possible_aborts_time", Help: "Transaction errors possible aborts time"},
	{ATSKey: "proxy.process.http.transaction_counts.errors.connect_failed", Name: "ats_http_transaction_errors_connect_failed_count", Help: "Transaction errors connect failed count"},
	{ATSKey: "proxy.process.http.transaction_totaltime.errors.connect_failed", Name: "ats_http_transaction_errors_connect_failed_time", Help: "Transaction errors connect failed time"},
	{ATSKey: "proxy.process.http.transaction_counts.errors.other", Name: "ats_http_transaction_errors_other_count", Help: "Transaction errors other count"},
	{ATSKey: "proxy.process.http.transaction_totaltime.errors.other", Name: "ats_http_transaction_errors_other_time", Help: "Transaction errors other time"},
	{ATSKey: "proxy.process.http.transaction_counts.other.unclassified", Name: "ats_http_transaction_other_unclassified_count", Help: "Transaction other unclassified count"},
	{ATSKey: "proxy.process.http.transaction_totaltime.other.unclassified", Name: "ats_http_transaction_other_unclassified_time", Help: "Transaction other unclassified time"},

	// HTTP Other
	{ATSKey: "proxy.process.http.disallowed_post_100_continue", Name: "ats_http_disallowed_post_100_continue", Help: "Disallowed POST with 100-continue"},
	{ATSKey: "proxy.process.http.total_x_redirect_count", Name: "ats_http_total_x_redirect_count", Help: "Total X-Redirect count"},
	{ATSKey: "proxy.process.http.origin_connections_throttled_out", Name: "ats_http_origin_connections_throttled_out", Help: "Origin connections throttled out"},
	{ATSKey: "proxy.process.http.post_body_too_large", Name: "ats_http_post_body_too_large", Help: "POST body too large"},

	// HTTP Milestones
	{ATSKey: "proxy.process.http.milestone.ua_begin", Name: "ats_http_milestone_ua_begin", Help: "Milestone: user agent begin"},
	{ATSKey: "proxy.process.http.milestone.ua_first_read", Name: "ats_http_milestone_ua_first_read", Help: "Milestone: user agent first read"},
	{ATSKey: "proxy.process.http.milestone.ua_read_header_done", Name: "ats_http_milestone_ua_read_header_done", Help: "Milestone: user agent read header done"},
	{ATSKey: "proxy.process.http.milestone.ua_begin_write", Name: "ats_http_milestone_ua_begin_write", Help: "Milestone: user agent begin write"},
	{ATSKey: "proxy.process.http.milestone.ua_close", Name: "ats_http_milestone_ua_close", Help: "Milestone: user agent close"},
	{ATSKey: "proxy.process.http.milestone.server_first_connect", Name: "ats_http_milestone_server_first_connect", Help: "Milestone: server first connect"},
	{ATSKey: "proxy.process.http.milestone.server_connect", Name: "ats_http_milestone_server_connect", Help: "Milestone: server connect"},
	{ATSKey: "proxy.process.http.milestone.server_connect_end", Name: "ats_http_milestone_server_connect_end", Help: "Milestone: server connect end"},
	{ATSKey: "proxy.process.http.milestone.server_begin_write", Name: "ats_http_milestone_server_begin_write", Help: "Milestone: server begin write"},
	{ATSKey: "proxy.process.http.milestone.server_first_read", Name: "ats_http_milestone_server_first_read", Help: "Milestone: server first read"},
	{ATSKey: "proxy.process.http.milestone.server_read_header_done", Name: "ats_http_milestone_server_read_header_done", Help: "Milestone: server read header done"},
	{ATSKey: "proxy.process.http.milestone.server_close", Name: "ats_http_milestone_server_close", Help: "Milestone: server close"},
	{ATSKey: "proxy.process.http.milestone.cache_open_read_begin", Name: "ats_http_milestone_cache_open_read_begin", Help: "Milestone: cache open read begin"},
	{ATSKey: "proxy.process.http.milestone.cache_open_read_end", Name: "ats_http_milestone_cache_open_read_end", Help: "Milestone: cache open read end"},
	{ATSKey: "proxy.process.http.milestone.cache_open_write_begin", Name: "ats_http_milestone_cache_open_write_begin", Help: "Milestone: cache open write begin"},
	{ATSKey: "proxy.process.http.milestone.cache_open_write_end", Name: "ats_http_milestone_cache_open_write_end", Help: "Milestone: cache open write end"},
	{ATSKey: "proxy.process.http.milestone.dns_lookup_begin", Name: "ats_http_milestone_dns_lookup_begin", Help: "Milestone: DNS lookup begin"},
	{ATSKey: "proxy.process.http.milestone.dns_lookup_end", Name: "ats_http_milestone_dns_lookup_end", Help: "Milestone: DNS lookup end"},
	{ATSKey: "proxy.process.http.milestone.sm_start", Name: "ats_http_milestone_sm_start", Help: "Milestone: state machine start"},
	{ATSKey: "proxy.process.http.milestone.sm_finish", Name: "ats_http_milestone_sm_finish", Help: "Milestone: state machine finish"},

	// Dead Server
	{ATSKey: "proxy.process.http.dead_server.no_requests", Name: "ats_http_dead_server_no_requests", Help: "Dead server no requests"},

	// HTTP/2
	{ATSKey: "proxy.process.http2.total_client_connections", Name: "ats_http2_total_client_connections", Help: "HTTP/2 total client connections"},
	{ATSKey: "proxy.process.http2.current_client_connections", Name: "ats_http2_current_client_connections", Help: "HTTP/2 current client connections"},
	{ATSKey: "proxy.process.http2.current_active_client_connections", Name: "ats_http2_current_active_client_connections", Help: "HTTP/2 current active client connections"},
	{ATSKey: "proxy.process.http2.total_client_streams", Name: "ats_http2_total_client_streams", Help: "HTTP/2 total client streams"},
	{ATSKey: "proxy.process.http2.current_client_streams", Name: "ats_http2_current_client_streams", Help: "HTTP/2 current client streams"},
	{ATSKey: "proxy.process.http2.total_transactions_time", Name: "ats_http2_total_transactions_time", Help: "HTTP/2 total transactions time"},
	{ATSKey: "proxy.process.http2.connection_errors", Name: "ats_http2_connection_errors", Help: "HTTP/2 connection errors"},
	{ATSKey: "proxy.process.http2.stream_errors", Name: "ats_http2_stream_errors", Help: "HTTP/2 stream errors"},
	{ATSKey: "proxy.process.http2.session_die_default", Name: "ats_http2_session_die_default", Help: "HTTP/2 session die default"},
	{ATSKey: "proxy.process.http2.session_die_other", Name: "ats_http2_session_die_other", Help: "HTTP/2 session die other"},
	{ATSKey: "proxy.process.http2.session_die_eos", Name: "ats_http2_session_die_eos", Help: "HTTP/2 session die EOS"},
	{ATSKey: "proxy.process.http2.session_die_active", Name: "ats_http2_session_die_active", Help: "HTTP/2 session die active"},
	{ATSKey: "proxy.process.http2.session_die_inactive", Name: "ats_http2_session_die_inactive", Help: "HTTP/2 session die inactive"},
	{ATSKey: "proxy.process.http2.session_die_error", Name: "ats_http2_session_die_error", Help: "HTTP/2 session die error"},
	{ATSKey: "proxy.process.http2.session_die_high_error_rate", Name: "ats_http2_session_die_high_error_rate", Help: "HTTP/2 session die high error rate"},
	{ATSKey: "proxy.process.http2.max_settings_per_frame_exceeded", Name: "ats_http2_max_settings_per_frame_exceeded", Help: "HTTP/2 max settings per frame exceeded"},
	{ATSKey: "proxy.process.http2.max_settings_per_minute_exceeded", Name: "ats_http2_max_settings_per_minute_exceeded", Help: "HTTP/2 max settings per minute exceeded"},
	{ATSKey: "proxy.process.http2.max_settings_frames_per_minute_exceeded", Name: "ats_http2_max_settings_frames_per_minute_exceeded", Help: "HTTP/2 max settings frames per minute exceeded"},
	{ATSKey: "proxy.process.http2.max_ping_frames_per_minute_exceeded", Name: "ats_http2_max_ping_frames_per_minute_exceeded", Help: "HTTP/2 max ping frames per minute exceeded"},
	{ATSKey: "proxy.process.http2.max_priority_frames_per_minute_exceeded", Name: "ats_http2_max_priority_frames_per_minute_exceeded", Help: "HTTP/2 max priority frames per minute exceeded"},
	{ATSKey: "proxy.process.http2.max_rst_stream_frames_per_minute_exceeded", Name: "ats_http2_max_rst_stream_frames_per_minute_exceeded", Help: "HTTP/2 max RST stream frames per minute exceeded"},
	{ATSKey: "proxy.process.http2.insufficient_avg_window_update", Name: "ats_http2_insufficient_avg_window_update", Help: "HTTP/2 insufficient average window update"},
	{ATSKey: "proxy.process.http2.max_concurrent_streams_exceeded_in", Name: "ats_http2_max_concurrent_streams_exceeded_in", Help: "HTTP/2 max concurrent streams exceeded incoming"},
	{ATSKey: "proxy.process.http2.max_concurrent_streams_exceeded_out", Name: "ats_http2_max_concurrent_streams_exceeded_out", Help: "HTTP/2 max concurrent streams exceeded outgoing"},

	// HTTPS
	{ATSKey: "proxy.process.https.total_client_connections", Name: "ats_https_total_client_connections", Help: "HTTPS total client connections"},
	{ATSKey: "proxy.process.https.incoming_requests", Name: "ats_https_incoming_requests", Help: "HTTPS incoming requests"},

	// Origin
	{ATSKey: "proxy.process.http.origin.reuse", Name: "ats_http_origin_reuse", Help: "Origin connections reused"},
	{ATSKey: "proxy.process.http.origin.not_found", Name: "ats_http_origin_not_found", Help: "Origin connections not found"},
	{ATSKey: "proxy.process.http.origin.reuse_fail", Name: "ats_http_origin_reuse_fail", Help: "Origin connections reuse failed"},
	{ATSKey: "proxy.process.http.origin.make_new", Name: "ats_http_origin_make_new", Help: "Origin connections made new"},
	{ATSKey: "proxy.process.http.origin.no_sharing", Name: "ats_http_origin_no_sharing", Help: "Origin connections no sharing"},
	{ATSKey: "proxy.process.http.origin.body", Name: "ats_http_origin_body", Help: "Origin connections with body"},
	{ATSKey: "proxy.process.http.origin.private", Name: "ats_http_origin_private", Help: "Origin private connections"},
	{ATSKey: "proxy.process.http.origin.close_private", Name: "ats_http_origin_close_private", Help: "Origin close private connections"},
	{ATSKey: "proxy.process.http.origin.raw", Name: "ats_http_origin_raw", Help: "Origin raw connections"},
	{ATSKey: "proxy.process.http.origin.connect.adjust_thread", Name: "ats_http_origin_connect_adjust_thread", Help: "Origin connect adjust thread"},
	{ATSKey: "proxy.process.http.cache.open_write.adjust_thread", Name: "ats_http_cache_open_write_adjust_thread", Help: "Cache open write adjust thread"},

	// Origin Shutdown
	{ATSKey: "proxy.process.http.origin_shutdown.pool_lock_contention", Name: "ats_http_origin_shutdown_pool_lock_contention", Help: "Origin shutdown pool lock contention"},
	{ATSKey: "proxy.process.http.origin_shutdown.migration_failure", Name: "ats_http_origin_shutdown_migration_failure", Help: "Origin shutdown migration failure"},
	{ATSKey: "proxy.process.http.origin_shutdown.tunnel_server", Name: "ats_http_origin_shutdown_tunnel_server", Help: "Origin shutdown tunnel server"},
	{ATSKey: "proxy.process.http.origin_shutdown.tunnel_server_no_keep_alive", Name: "ats_http_origin_shutdown_tunnel_server_no_keep_alive", Help: "Origin shutdown tunnel server no keep alive"},
	{ATSKey: "proxy.process.http.origin_shutdown.tunnel_server_eos", Name: "ats_http_origin_shutdown_tunnel_server_eos", Help: "Origin shutdown tunnel server EOS"},
	{ATSKey: "proxy.process.http.origin_shutdown.tunnel_server_plugin_tunnel", Name: "ats_http_origin_shutdown_tunnel_server_plugin_tunnel", Help: "Origin shutdown tunnel server plugin tunnel"},
	{ATSKey: "proxy.process.http.origin_shutdown.tunnel_server_detach", Name: "ats_http_origin_shutdown_tunnel_server_detach", Help: "Origin shutdown tunnel server detach"},
	{ATSKey: "proxy.process.http.origin_shutdown.tunnel_client", Name: "ats_http_origin_shutdown_tunnel_client", Help: "Origin shutdown tunnel client"},
	{ATSKey: "proxy.process.http.origin_shutdown.tunnel_transform_read", Name: "ats_http_origin_shutdown_tunnel_transform_read", Help: "Origin shutdown tunnel transform read"},
	{ATSKey: "proxy.process.http.origin_shutdown.release_no_sharing", Name: "ats_http_origin_shutdown_release_no_sharing", Help: "Origin shutdown release no sharing"},
	{ATSKey: "proxy.process.http.origin_shutdown.release_no_server", Name: "ats_http_origin_shutdown_release_no_server", Help: "Origin shutdown release no server"},
	{ATSKey: "proxy.process.http.origin_shutdown.release_no_keep_alive", Name: "ats_http_origin_shutdown_release_no_keep_alive", Help: "Origin shutdown release no keep alive"},
	{ATSKey: "proxy.process.http.origin_shutdown.release_invalid_response", Name: "ats_http_origin_shutdown_release_invalid_response", Help: "Origin shutdown release invalid response"},
	{ATSKey: "proxy.process.http.origin_shutdown.release_invalid_request", Name: "ats_http_origin_shutdown_release_invalid_request", Help: "Origin shutdown release invalid request"},
	{ATSKey: "proxy.process.http.origin_shutdown.release_modified", Name: "ats_http_origin_shutdown_release_modified", Help: "Origin shutdown release modified"},
	{ATSKey: "proxy.process.http.origin_shutdown.release_misc", Name: "ats_http_origin_shutdown_release_misc", Help: "Origin shutdown release misc"},
	{ATSKey: "proxy.process.http.origin_shutdown.cleanup_entry", Name: "ats_http_origin_shutdown_cleanup_entry", Help: "Origin shutdown cleanup entry"},
	{ATSKey: "proxy.process.http.origin_shutdown.tunnel_abort", Name: "ats_http_origin_shutdown_tunnel_abort", Help: "Origin shutdown tunnel abort"},

	// Cache (proxy.process.cache)
	{ATSKey: "proxy.process.cache.bytes_total", Name: "ats_cache_bytes_total", Help: "Total cache bytes"},
	{ATSKey: "proxy.process.cache.bytes_used", Name: "ats_cache_bytes_used", Help: "Used cache bytes"},
	{ATSKey: "proxy.process.cache.ram_cache.total_bytes", Name: "ats_cache_ram_total_bytes", Help: "Total RAM cache bytes"},
	{ATSKey: "proxy.process.cache.ram_cache.bytes_used", Name: "ats_cache_ram_bytes_used", Help: "Used RAM cache bytes"},
	{ATSKey: "proxy.process.cache.read.active", Name: "ats_cache_read_active", Help: "Active cache reads"},
	{ATSKey: "proxy.process.cache.write.active", Name: "ats_cache_write_active", Help: "Active cache writes"},
	{ATSKey: "proxy.process.cache.lookup.active", Name: "ats_cache_lookup_active", Help: "Active cache lookups"},
	{ATSKey: "proxy.process.cache.remove.active", Name: "ats_cache_remove_active", Help: "Active cache removes"},
	{ATSKey: "proxy.process.cache.scan.active", Name: "ats_cache_scan_active", Help: "Active cache scans"},
	{ATSKey: "proxy.process.cache.update.active", Name: "ats_cache_update_active", Help: "Active cache updates"},
	{ATSKey: "proxy.process.cache.read.success", Name: "ats_cache_read_success", Help: "Successful cache reads"},
	{ATSKey: "proxy.process.cache.read.failure", Name: "ats_cache_read_failure", Help: "Failed cache reads"},
	{ATSKey: "proxy.process.cache.write.success", Name: "ats_cache_write_success", Help: "Successful cache writes"},
	{ATSKey: "proxy.process.cache.write.failure", Name: "ats_cache_write_failure", Help: "Failed cache writes"},
	{ATSKey: "proxy.process.cache.lookup.success", Name: "ats_cache_lookup_success", Help: "Successful cache lookups"},
	{ATSKey: "proxy.process.cache.lookup.failure", Name: "ats_cache_lookup_failure", Help: "Failed cache lookups"},
	{ATSKey: "proxy.process.cache.update.success", Name: "ats_cache_update_success", Help: "Successful cache updates"},
	{ATSKey: "proxy.process.cache.update.failure", Name: "ats_cache_update_failure", Help: "Failed cache updates"},
	{ATSKey: "proxy.process.cache.remove.success", Name: "ats_cache_remove_success", Help: "Successful cache removes"},
	{ATSKey: "proxy.process.cache.remove.failure", Name: "ats_cache_remove_failure", Help: "Failed cache removes"},
	{ATSKey: "proxy.process.cache.scan.success", Name: "ats_cache_scan_success", Help: "Successful cache scans"},
	{ATSKey: "proxy.process.cache.scan.failure", Name: "ats_cache_scan_failure", Help: "Failed cache scans"},
	{ATSKey: "proxy.process.cache.read_per_sec", Name: "ats_cache_read_per_sec", Help: "Cache reads per second"},
	{ATSKey: "proxy.process.cache.write_per_sec", Name: "ats_cache_write_per_sec", Help: "Cache writes per second"},
	{ATSKey: "proxy.process.cache.KB_read_per_sec", Name: "ats_cache_kb_read_per_sec", Help: "Cache KB read per second"},
	{ATSKey: "proxy.process.cache.KB_write_per_sec", Name: "ats_cache_kb_write_per_sec", Help: "Cache KB write per second"},

	// Network (proxy.process.net)
	{ATSKey: "proxy.process.net.connections_currently_open", Name: "ats_net_connections_currently_open", Help: "Currently open connections"},
	{ATSKey: "proxy.process.net.write_bytes", Name: "ats_net_write_bytes", Help: "Network bytes written"},
	{ATSKey: "proxy.process.net.calls_to_read", Name: "ats_net_calls_to_read", Help: "Calls to read"},
	{ATSKey: "proxy.process.net.calls_to_write", Name: "ats_net_calls_to_write", Help: "Calls to write"},
	{ATSKey: "proxy.process.net.calls_to_writetonet", Name: "ats_net_calls_to_writetonet", Help: "Calls to write to net"},
	{ATSKey: "proxy.process.net.calls_to_readfromnet_afterpoll", Name: "ats_net_calls_to_readfromnet_afterpoll", Help: "Calls to read from net after poll"},
	{ATSKey: "proxy.process.net.calls_to_read_nodata", Name: "ats_net_calls_to_read_nodata", Help: "Calls to read no data"},

	// HostDB (proxy.process.hostdb)
	{ATSKey: "proxy.process.hostdb.total_lookups", Name: "ats_hostdb_total_lookups", Help: "HostDB total lookups"},
	{ATSKey: "proxy.process.hostdb.total_hits", Name: "ats_hostdb_total_hits", Help: "HostDB total hits"},
	{ATSKey: "proxy.process.hostdb.ttl_expires", Name: "ats_hostdb_ttl_expires", Help: "HostDB TTL expires"},
	{ATSKey: "proxy.process.hostdb.bytes", Name: "ats_hostdb_bytes", Help: "HostDB bytes"},

	// Log (proxy.process.log)
	{ATSKey: "proxy.process.log.bytes_written_to_disk", Name: "ats_log_bytes_written_to_disk", Help: "Log bytes written to disk"},
	{ATSKey: "proxy.process.log.num_flush_to_disk", Name: "ats_log_num_flush_to_disk", Help: "Log number of flush to disk"},
	{ATSKey: "proxy.process.log.num_received_from_network", Name: "ats_log_num_received_from_network", Help: "Log number received from network"},
	{ATSKey: "proxy.process.log.num_sent_to_network", Name: "ats_log_num_sent_to_network", Help: "Log number sent to network"},
	{ATSKey: "proxy.process.log.bytes_lost_before_preproc", Name: "ats_log_bytes_lost_before_preproc", Help: "Log bytes lost before preprocessing"},
	{ATSKey: "proxy.process.log.bytes_lost_before_flush_to_disk", Name: "ats_log_bytes_lost_before_flush_to_disk", Help: "Log bytes lost before flush to disk"},
	{ATSKey: "proxy.process.log.bytes_lost_before_sent_to_network", Name: "ats_log_bytes_lost_before_sent_to_network", Help: "Log bytes lost before sent to network"},
	{ATSKey: "proxy.process.log.event_log_access_ok", Name: "ats_log_event_log_access_ok", Help: "Event log access OK"},
	{ATSKey: "proxy.process.log.event_log_access_aggr", Name: "ats_log_event_log_access_aggr", Help: "Event log access aggregated"},
	{ATSKey: "proxy.process.log.event_log_access_full", Name: "ats_log_event_log_access_full", Help: "Event log access full"},
	{ATSKey: "proxy.process.log.event_log_error_aggr", Name: "ats_log_event_log_error_aggr", Help: "Event log error aggregated"},
	{ATSKey: "proxy.process.log.event_log_error_full", Name: "ats_log_event_log_error_full", Help: "Event log error full"},

	// SOCKS
	{ATSKey: "proxy.process.socks.connections_unsuccessful", Name: "ats_socks_connections_unsuccessful", Help: "Unsuccessful SOCKS connections"},

	// Cluster
	{ATSKey: "proxy.process.cluster.nodes", Name: "ats_cluster_nodes", Help: "Cluster nodes"},
	{ATSKey: "proxy.process.cluster.connections_opened", Name: "ats_cluster_connections_opened", Help: "Cluster connections opened"},
	{ATSKey: "proxy.process.cluster.connections_bumped", Name: "ats_cluster_connections_bumped", Help: "Cluster connections bumped"},
	{ATSKey: "proxy.process.cluster.connections_write_locked", Name: "ats_cluster_connections_write_locked", Help: "Cluster connections write locked"},
	{ATSKey: "proxy.process.cluster.read_bytes", Name: "ats_cluster_read_bytes", Help: "Cluster read bytes"},
	{ATSKey: "proxy.process.cluster.configuration_changes", Name: "ats_cluster_configuration_changes", Help: "Cluster configuration changes"},
}
