package main

type MetricDefinition struct {
	ATSKey string
	Name   string
	Help   string
}

var MetricDefinitions = []MetricDefinition{
	{ATSKey: "global.proxy.process.http.total_client_connections", Name: "ats_proxy_process_http_total_client_connections", Help: "Total number of client connections"},
	{ATSKey: "global.proxy.process.http.server_transaction_time", Name: "ats_proxy_process_http_server_transaction_time", Help: "Server transaction time"},
	{ATSKey: "global.proxy.process.http.current_active_client_connections", Name: "ats_proxy_process_http_current_active_client_connections", Help: "Current active client connections"},
	{ATSKey: "global.proxy.process.http.current_server_connections", Name: "ats_proxy_process_http_current_server_connections", Help: "Current server connections"},
	{ATSKey: "global.proxy.process.http.current_cache_connections", Name: "ats_proxy_process_http_current_cache_connections", Help: "Current cache connections"},
	{ATSKey: "global.proxy.process.http.incoming_requests", Name: "ats_proxy_process_http_incoming_requests", Help: "Incoming HTTP requests"},
	{ATSKey: "global.proxy.process.http.outgoing_requests", Name: "ats_proxy_process_http_outgoing_requests", Help: "Outgoing HTTP requests"},
	{ATSKey: "global.proxy.process.http.get_requests", Name: "ats_proxy_process_http_get_requests", Help: "GET requests"},
	{ATSKey: "global.proxy.process.http.head_requests", Name: "ats_proxy_process_http_head_requests", Help: "HEAD requests"},
	{ATSKey: "global.proxy.process.http.post_requests", Name: "ats_proxy_process_http_post_requests", Help: "POST requests"},
	{ATSKey: "global.proxy.process.http.put_requests", Name: "ats_proxy_process_http_put_requests", Help: "PUT requests"},
	{ATSKey: "global.proxy.process.http.delete_requests", Name: "ats_proxy_process_http_delete_requests", Help: "DELETE requests"},
	{ATSKey: "global.proxy.process.http.options_requests", Name: "ats_proxy_process_http_options_requests", Help: "OPTIONS requests"},
	{ATSKey: "global.proxy.process.http.trace_requests", Name: "ats_proxy_process_http_trace_requests", Help: "TRACE requests"},
	{ATSKey: "global.proxy.process.http.connect_requests", Name: "ats_proxy_process_http_connect_requests", Help: "CONNECT requests"},
	{ATSKey: "global.proxy.process.http.1xx_responses", Name: "ats_proxy_process_http_1xx_responses", Help: "1xx responses"},
	{ATSKey: "global.proxy.process.http.2xx_responses", Name: "ats_proxy_process_http_2xx_responses", Help: "2xx responses"},
	{ATSKey: "global.proxy.process.http.3xx_responses", Name: "ats_proxy_process_http_3xx_responses", Help: "3xx responses"},
	{ATSKey: "global.proxy.process.http.4xx_responses", Name: "ats_proxy_process_http_4xx_responses", Help: "4xx responses"},
	{ATSKey: "global.proxy.process.http.5xx_responses", Name: "ats_proxy_process_http_5xx_responses", Help: "5xx responses"},
	{ATSKey: "global.proxy.process.http.200_responses", Name: "ats_proxy_process_http_200_responses", Help: "200 responses"},
	{ATSKey: "global.proxy.process.http.201_responses", Name: "ats_proxy_process_http_201_responses", Help: "201 responses"},
	{ATSKey: "global.proxy.process.http.202_responses", Name: "ats_proxy_process_http_202_responses", Help: "202 responses"},
	{ATSKey: "global.proxy.process.http.203_responses", Name: "ats_proxy_process_http_203_responses", Help: "203 responses"},
	{ATSKey: "global.proxy.process.http.204_responses", Name: "ats_proxy_process_http_204_responses", Help: "204 responses"},
	{ATSKey: "global.proxy.process.http.205_responses", Name: "ats_proxy_process_http_205_responses", Help: "205 responses"},
	{ATSKey: "global.proxy.process.http.206_responses", Name: "ats_proxy_process_http_206_responses", Help: "206 responses"},
	{ATSKey: "global.proxy.process.http.300_responses", Name: "ats_proxy_process_http_300_responses", Help: "300 responses"},
	{ATSKey: "global.proxy.process.http.301_responses", Name: "ats_proxy_process_http_301_responses", Help: "301 responses"},
	{ATSKey: "global.proxy.process.http.302_responses", Name: "ats_proxy_process_http_302_responses", Help: "302 responses"},
	{ATSKey: "global.proxy.process.http.303_responses", Name: "ats_proxy_process_http_303_responses", Help: "303 responses"},
	{ATSKey: "global.proxy.process.http.304_responses", Name: "ats_proxy_process_http_304_responses", Help: "304 responses"},
	{ATSKey: "global.proxy.process.http.305_responses", Name: "ats_proxy_process_http_305_responses", Help: "305 responses"},
	{ATSKey: "global.proxy.process.http.307_responses", Name: "ats_proxy_process_http_307_responses", Help: "307 responses"},
	{ATSKey: "global.proxy.process.http.308_responses", Name: "ats_proxy_process_http_308_responses", Help: "308 responses"},
	{ATSKey: "global.proxy.process.http.400_responses", Name: "ats_proxy_process_http_400_responses", Help: "400 responses"},
	{ATSKey: "global.proxy.process.http.401_responses", Name: "ats_proxy_process_http_401_responses", Help: "401 responses"},
	{ATSKey: "global.proxy.process.http.402_responses", Name: "ats_proxy_process_http_402_responses", Help: "402 responses"},
	{ATSKey: "global.proxy.process.http.403_responses", Name: "ats_proxy_process_http_403_responses", Help: "403 responses"},
	{ATSKey: "global.proxy.process.http.404_responses", Name: "ats_proxy_process_http_404_responses", Help: "404 responses"},
	{ATSKey: "global.proxy.process.http.405_responses", Name: "ats_proxy_process_http_405_responses", Help: "405 responses"},
	{ATSKey: "global.proxy.process.http.406_responses", Name: "ats_proxy_process_http_406_responses", Help: "406 responses"},
	{ATSKey: "global.proxy.process.http.407_responses", Name: "ats_proxy_process_http_407_responses", Help: "407 responses"},
	{ATSKey: "global.proxy.process.http.408_responses", Name: "ats_proxy_process_http_408_responses", Help: "408 responses"},
	{ATSKey: "global.proxy.process.http.409_responses", Name: "ats_proxy_process_http_409_responses", Help: "409 responses"},
	{ATSKey: "global.proxy.process.http.410_responses", Name: "ats_proxy_process_http_410_responses", Help: "410 responses"},
	{ATSKey: "global.proxy.process.http.411_responses", Name: "ats_proxy_process_http_411_responses", Help: "411 responses"},
	{ATSKey: "global.proxy.process.http.412_responses", Name: "ats_proxy_process_http_412_responses", Help: "412 responses"},
	{ATSKey: "global.proxy.process.http.413_responses", Name: "ats_proxy_process_http_413_responses", Help: "413 responses"},
	{ATSKey: "global.proxy.process.http.414_responses", Name: "ats_proxy_process_http_414_responses", Help: "414 responses"},
	{ATSKey: "global.proxy.process.http.415_responses", Name: "ats_proxy_process_http_415_responses", Help: "415 responses"},
	{ATSKey: "global.proxy.process.http.416_responses", Name: "ats_proxy_process_http_416_responses", Help: "416 responses"},
	{ATSKey: "global.proxy.process.http.4xx_responses", Name: "ats_proxy_process_http_4xx_responses", Help: "4xx responses"},
	{ATSKey: "global.proxy.process.http.500_responses", Name: "ats_proxy_process_http_500_responses", Help: "500 responses"},
	{ATSKey: "global.proxy.process.http.501_responses", Name: "ats_proxy_process_http_501_responses", Help: "501 responses"},
	{ATSKey: "global.proxy.process.http.502_responses", Name: "ats_proxy_process_http_502_responses", Help: "502 responses"},
	{ATSKey: "global.proxy.process.http.503_responses", Name: "ats_proxy_process_http_503_responses", Help: "503 responses"},
	{ATSKey: "global.proxy.process.http.504_responses", Name: "ats_proxy_process_http_504_responses", Help: "504 responses"},
	{ATSKey: "global.proxy.process.http.505_responses", Name: "ats_proxy_process_http_505_responses", Help: "505 responses"},
	{ATSKey: "global.proxy.process.http.broken_server_connections", Name: "ats_proxy_process_http_broken_server_connections", Help: "Broken server connections"},
	{ATSKey: "global.proxy.process.http.cache_hit_ims", Name: "ats_proxy_process_http_cache_hit_ims", Help: "Cache hit IMS"},
	{ATSKey: "global.proxy.process.http.cache_hit_stale_served", Name: "ats_proxy_process_http_cache_hit_stale_served", Help: "Cache hit stale served"},
	{ATSKey: "global.proxy.process.http.cache_lookups", Name: "ats_proxy_process_http_cache_lookups", Help: "Cache lookups"},
	{ATSKey: "global.proxy.process.http.cache_miss_changed", Name: "ats_proxy_process_http_cache_miss_changed", Help: "Cache miss changed"},
	{ATSKey: "global.proxy.process.http.cache_miss_cold", Name: "ats_proxy_process_http_cache_miss_cold", Help: "Cache miss cold"},
	{ATSKey: "global.proxy.process.http.cache_writes", Name: "ats_proxy_process_http_cache_writes", Help: "Cache writes"},
	{ATSKey: "global.proxy.process.http.client_no_cache_requests", Name: "ats_proxy_process_http_client_no_cache_requests", Help: "Client no-cache requests"},
	{ATSKey: "global.proxy.process.http.client_write_time", Name: "ats_proxy_process_http_client_write_time", Help: "Client write time"},
	{ATSKey: "global.proxy.process.http.tunnels", Name: "ats_proxy_process_http_tunnels", Help: "HTTP tunnels"},
	{ATSKey: "global.proxy.process.http.user_agent_request_header_total_size", Name: "ats_proxy_process_http_user_agent_request_header_total_size", Help: "User agent request header total size"},
	{ATSKey: "global.proxy.process.http.user_agent_request_document_total_size", Name: "ats_proxy_process_http_user_agent_request_document_total_size", Help: "User agent request document total size"},
	{ATSKey: "global.proxy.process.http.origin_server_response_header_total_size", Name: "ats_proxy_process_http_origin_server_response_header_total_size", Help: "Origin server response header total size"},
	{ATSKey: "global.proxy.process.http.origin_server_request_header_total_size", Name: "ats_proxy_process_http_origin_server_request_header_total_size", Help: "Origin server request header total size"},
	{ATSKey: "global.proxy.process.cache.bytes_total", Name: "ats_proxy_process_cache_bytes_total", Help: "Total cache bytes"},
	{ATSKey: "global.proxy.process.cache.bytes_used", Name: "ats_proxy_process_cache_bytes_used", Help: "Used cache bytes"},
	{ATSKey: "global.proxy.process.cache.ram_cache.total_bytes", Name: "ats_proxy_process_cache_ram_cache_total_bytes", Help: "Total RAM cache bytes"},
	{ATSKey: "global.proxy.process.cache.ram_cache.bytes_used", Name: "ats_proxy_process_cache_ram_cache_bytes_used", Help: "Used RAM cache bytes"},
	{ATSKey: "global.proxy.process.cache.read.active", Name: "ats_proxy_process_cache_read_active", Help: "Active cache reads"},
	{ATSKey: "global.proxy.process.cache.write.active", Name: "ats_proxy_process_cache_write_active", Help: "Active cache writes"},
	{ATSKey: "global.proxy.process.cache.lookup.active", Name: "ats_proxy_process_cache_lookup_active", Help: "Active cache lookups"},
	{ATSKey: "global.proxy.process.cache.remove.active", Name: "ats_proxy_process_cache_remove_active", Help: "Active cache removes"},
	{ATSKey: "global.proxy.process.cache.scan.active", Name: "ats_proxy_process_cache_scan_active", Help: "Active cache scans"},
	{ATSKey: "global.proxy.process.cache.update.active", Name: "ats_proxy_process_cache_update_active", Help: "Active cache updates"},
	{ATSKey: "global.proxy.process.cache.read.success", Name: "ats_proxy_process_cache_read_success", Help: "Successful cache reads"},
	{ATSKey: "global.proxy.process.cache.read.failure", Name: "ats_proxy_process_cache_read_failure", Help: "Failed cache reads"},
	{ATSKey: "global.proxy.process.cache.write.success", Name: "ats_proxy_process_cache_write_success", Help: "Successful cache writes"},
	{ATSKey: "global.proxy.process.cache.write.failure", Name: "ats_proxy_process_cache_write_failure", Help: "Failed cache writes"},
	{ATSKey: "global.proxy.process.cache.lookup.success", Name: "ats_proxy_process_cache_lookup_success", Help: "Successful cache lookups"},
	{ATSKey: "global.proxy.process.cache.lookup.failure", Name: "ats_proxy_process_cache_lookup_failure", Help: "Failed cache lookups"},
	{ATSKey: "global.proxy.process.cache.update.success", Name: "ats_proxy_process_cache_update_success", Help: "Successful cache updates"},
	{ATSKey: "global.proxy.process.cache.update.failure", Name: "ats_proxy_process_cache_update_failure", Help: "Failed cache updates"},
	{ATSKey: "global.proxy.process.cache.remove.success", Name: "ats_proxy_process_cache_remove_success", Help: "Successful cache removes"},
	{ATSKey: "global.proxy.process.cache.remove.failure", Name: "ats_proxy_process_cache_remove_failure", Help: "Failed cache removes"},
	{ATSKey: "global.proxy.process.cache.scan.success", Name: "ats_proxy_process_cache_scan_success", Help: "Successful cache scans"},
	{ATSKey: "global.proxy.process.cache.scan.failure", Name: "ats_proxy_process_cache_scan_failure", Help: "Failed cache scans"},
	{ATSKey: "global.proxy.process.cache.read_per_sec", Name: "ats_proxy_process_cache_read_per_sec", Help: "Cache reads per second"},
	{ATSKey: "global.proxy.process.cache.write_per_sec", Name: "ats_proxy_process_cache_write_per_sec", Help: "Cache writes per second"},
	{ATSKey: "global.proxy.process.cache.KB_read_per_sec", Name: "ats_proxy_process_cache_kb_read_per_sec", Help: "Cache KB read per second"},
	{ATSKey: "global.proxy.process.cache.KB_write_per_sec", Name: "ats_proxy_process_cache_kb_write_per_sec", Help: "Cache KB write per second"},
	{ATSKey: "global.proxy.process.net.connections_currently_open", Name: "ats_proxy_process_net_connections_currently_open", Help: "Currently open connections"},
	{ATSKey: "global.proxy.process.net.write_bytes", Name: "ats_proxy_process_net_write_bytes", Help: "Network bytes written"},
	{ATSKey: "global.proxy.process.net.calls_to_read", Name: "ats_proxy_process_net_calls_to_read", Help: "Calls to read"},
	{ATSKey: "global.proxy.process.net.calls_to_write", Name: "ats_proxy_process_net_calls_to_write", Help: "Calls to write"},
	{ATSKey: "global.proxy.process.net.calls_to_writetonet", Name: "ats_proxy_process_net_calls_to_writetonet", Help: "Calls to write to net"},
	{ATSKey: "global.proxy.process.net.calls_to_readfromnet_afterpoll", Name: "ats_proxy_process_net_calls_to_readfromnet_afterpoll", Help: "Calls to read from net after poll"},
	{ATSKey: "global.proxy.process.net.calls_to_read_nodata", Name: "ats_proxy_process_net_calls_to_read_nodata", Help: "Calls to read no data"},
	{ATSKey: "global.proxy.node.current_client_connections", Name: "ats_proxy_node_current_client_connections", Help: "Current client connections"},
	{ATSKey: "global.proxy.node.cache_total_hits", Name: "ats_proxy_node_cache_total_hits", Help: "Total cache hits"},
	{ATSKey: "global.proxy.node.cache_total_misses", Name: "ats_proxy_node_cache_total_misses", Help: "Total cache misses"},
	{ATSKey: "global.proxy.node.cache_hit_ratio", Name: "ats_proxy_node_cache_hit_ratio", Help: "Cache hit ratio"},
	{ATSKey: "global.proxy.node.cache_hit_ratio_int_pct", Name: "ats_proxy_node_cache_hit_ratio_int_pct", Help: "Cache hit ratio integer percentage"},
	{ATSKey: "global.proxy.node.bandwidth_hit_ratio_int_pct", Name: "ats_proxy_node_bandwidth_hit_ratio_int_pct", Help: "Bandwidth hit ratio integer percentage"},
	{ATSKey: "global.proxy.node.cache.bytes_total", Name: "ats_proxy_node_cache_bytes_total", Help: "Total cache bytes"},
	{ATSKey: "global.proxy.node.cache.bytes_free", Name: "ats_proxy_node_cache_bytes_free", Help: "Free cache bytes"},
	{ATSKey: "global.proxy.node.cache.bytes_total_mb", Name: "ats_proxy_node_cache_bytes_total_mb", Help: "Total cache bytes in MB"},
	{ATSKey: "global.proxy.node.cache.bytes_free_mb", Name: "ats_proxy_node_cache_bytes_free_mb", Help: "Free cache bytes in MB"},
	{ATSKey: "global.proxy.node.cache.percent_free", Name: "ats_proxy_node_cache_percent_free", Help: "Percentage of cache free"},
	{ATSKey: "global.proxy.node.http.origin_server_current_connections_count", Name: "ats_proxy_node_http_origin_server_current_connections_count", Help: "Origin server current connections count"},
	{ATSKey: "global.proxy.node.http.user_agent_xacts_per_second", Name: "ats_proxy_node_http_user_agent_xacts_per_second", Help: "User agent transactions per second"},
	{ATSKey: "global.proxy.node.http.throughput", Name: "ats_proxy_node_http_throughput", Help: "HTTP throughput"},
	{ATSKey: "global.proxy.node.http.parent_proxy_total_response_bytes", Name: "ats_proxy_node_http_parent_proxy_total_response_bytes", Help: "Parent proxy total response bytes"},
	{ATSKey: "global.proxy.node.http.parent_proxy_total_request_bytes", Name: "ats_proxy_node_http_parent_proxy_total_request_bytes", Help: "Parent proxy total request bytes"},
	{ATSKey: "global.proxy.node.http.user_agent_total_response_bytes", Name: "ats_proxy_node_http_user_agent_total_response_bytes", Help: "User agent total response bytes"},
	{ATSKey: "global.proxy.node.http.user_agent_total_request_bytes", Name: "ats_proxy_node_http_user_agent_total_request_bytes", Help: "User agent total request bytes"},
	{ATSKey: "global.proxy.node.origin_server_total_bytes", Name: "ats_proxy_node_origin_server_total_bytes", Help: "Origin server total bytes"},
	{ATSKey: "global.proxy.node.user_agent_total_bytes", Name: "ats_proxy_node_user_agent_total_bytes", Help: "User agent total bytes"},
	{ATSKey: "global.proxy.node.dns.lookup_avg_time_ms", Name: "ats_proxy_node_dns_lookup_avg_time_ms", Help: "DNS lookup average time in ms"},
	{ATSKey: "global.proxy.node.dns.lookups_per_second", Name: "ats_proxy_node_dns_lookups_per_second", Help: "DNS lookups per second"},
	{ATSKey: "global.proxy.node.hostdb.total_hits", Name: "ats_proxy_node_hostdb_total_hits", Help: "HostDB total hits"},
	{ATSKey: "global.proxy.node.hostdb.total_lookups", Name: "ats_proxy_node_hostdb_total_lookups", Help: "HostDB total lookups"},
	{ATSKey: "global.proxy.node.hostdb.hit_ratio_avg_10s", Name: "ats_proxy_node_hostdb_hit_ratio_avg_10s", Help: "HostDB hit ratio average 10s"},
	{ATSKey: "global.proxy.process.hostdb.total_lookups", Name: "ats_proxy_process_hostdb_total_lookups", Help: "Process HostDB total lookups"},
	{ATSKey: "global.proxy.process.hostdb.total_hits", Name: "ats_proxy_process_hostdb_total_hits", Help: "Process HostDB total hits"},
	{ATSKey: "global.proxy.process.hostdb.ttl_expires", Name: "ats_proxy_process_hostdb_ttl_expires", Help: "Process HostDB TTL expires"},
	{ATSKey: "global.proxy.process.hostdb.bytes", Name: "ats_proxy_process_hostdb_bytes", Help: "Process HostDB bytes"},
	{ATSKey: "global.proxy.node.num_processes", Name: "ats_proxy_node_num_processes", Help: "Number of processes"},
	{ATSKey: "global.proxy.process.socks.connections_unsuccessful", Name: "ats_proxy_process_socks_connections_unsuccessful", Help: "Unsuccessful SOCKS connections"},
	{ATSKey: "global.proxy.process.update.successes", Name: "ats_proxy_process_update_successes", Help: "Update successes"},
	{ATSKey: "global.proxy.process.congestion.congested_on_max_connection", Name: "ats_proxy_process_congestion_congested_on_max_connection", Help: "Congested on max connection"},
	{ATSKey: "global.proxy.process.cluster.nodes", Name: "ats_proxy_process_cluster_nodes", Help: "Cluster nodes"},
	{ATSKey: "global.proxy.process.cluster.connections_opened", Name: "ats_proxy_process_cluster_connections_opened", Help: "Cluster connections opened"},
	{ATSKey: "global.proxy.process.cluster.connections_bumped", Name: "ats_proxy_process_cluster_connections_bumped", Help: "Cluster connections bumped"},
	{ATSKey: "global.proxy.process.cluster.connections_write_locked", Name: "ats_proxy_process_cluster_connections_write_locked", Help: "Cluster connections write locked"},
	{ATSKey: "global.proxy.process.cluster.read_bytes", Name: "ats_proxy_process_cluster_read_bytes", Help: "Cluster read bytes"},
	{ATSKey: "global.proxy.process.cluster.configuration_changes", Name: "ats_proxy_process_cluster_configuration_changes", Help: "Cluster configuration changes"},
	{ATSKey: "global.proxy.process.log.bytes_written_to_disk", Name: "ats_proxy_process_log_bytes_written_to_disk", Help: "Log bytes written to disk"},
	{ATSKey: "global.proxy.process.log.num_flush_to_disk", Name: "ats_proxy_process_log_num_flush_to_disk", Help: "Log number of flush to disk"},
	{ATSKey: "global.proxy.process.log.num_received_from_network", Name: "ats_proxy_process_log_num_received_from_network", Help: "Log number received from network"},
	{ATSKey: "global.proxy.process.log.num_sent_to_network", Name: "ats_proxy_process_log_num_sent_to_network", Help: "Log number sent to network"},
	{ATSKey: "global.proxy.process.log.bytes_lost_before_preproc", Name: "ats_proxy_process_log_bytes_lost_before_preproc", Help: "Log bytes lost before preprocessing"},
	{ATSKey: "global.proxy.process.log.bytes_lost_before_flush_to_disk", Name: "ats_proxy_process_log_bytes_lost_before_flush_to_disk", Help: "Log bytes lost before flush to disk"},
	{ATSKey: "global.proxy.process.log.bytes_lost_before_sent_to_network", Name: "ats_proxy_process_log_bytes_lost_before_sent_to_network", Help: "Log bytes lost before sent to network"},
	{ATSKey: "global.proxy.process.log.event_log_access_ok", Name: "ats_proxy_process_log_event_log_access_ok", Help: "Event log access OK"},
	{ATSKey: "global.proxy.process.log.event_log_access_aggr", Name: "ats_proxy_process_log_event_log_access_aggr", Help: "Event log access aggregated"},
	{ATSKey: "global.proxy.process.log.event_log_access_full", Name: "ats_proxy_process_log_event_log_access_full", Help: "Event log access full"},
	{ATSKey: "global.proxy.process.log.event_log_error_aggr", Name: "ats_proxy_process_log_event_log_error_aggr", Help: "Event log error aggregated"},
	{ATSKey: "global.proxy.process.log.event_log_error_full", Name: "ats_proxy_process_log_event_log_error_full", Help: "Event log error full"},
	{ATSKey: "global.proxy.node.log.event_log_access_full", Name: "ats_proxy_node_log_event_log_access_full", Help: "Node event log access full"},
	{ATSKey: "global.proxy.node.log.event_log_access_fail", Name: "ats_proxy_node_log_event_log_access_fail", Help: "Node event log access fail"},
	{ATSKey: "global.proxy.node.log.event_log_error_full", Name: "ats_proxy_node_log_event_log_error_full", Help: "Node event log error full"},
	{ATSKey: "global.proxy.node.log.event_log_error_fail", Name: "ats_proxy_node_log_event_log_error_fail", Help: "Node event log error fail"},
	{ATSKey: "global.proxy.node.log.bytes_sent_to_network", Name: "ats_proxy_node_log_bytes_sent_to_network", Help: "Node log bytes sent to network"},
	{ATSKey: "global.proxy.node.log.bytes_received_from_network_avg_10s", Name: "ats_proxy_node_log_bytes_received_from_network_avg_10s", Help: "Node log bytes received from network avg 10s"},
	{ATSKey: "global.proxy.node.log.bytes_lost_before_written_to_disk", Name: "ats_proxy_node_log_bytes_lost_before_written_to_disk", Help: "Node log bytes lost before written to disk"},
	{ATSKey: "global.proxy.node.log.num_flush_to_disk", Name: "ats_proxy_node_log_num_flush_to_disk", Help: "Node log num flush to disk"},
	{ATSKey: "global.proxy.node.log.num_received_from_network", Name: "ats_proxy_node_log_num_received_from_network", Help: "Node log num received from network"},
}